<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		$counties = [
			['name' => 'Afghanistan', 'code' => 'AF', 'e164_code' => '+93'],
			['name' => 'Albania', 'code' => 'AL', 'e164_code' => '+355'],
			['name' => 'Algeria', 'code' => 'DZ', 'e164_code' => '+213'],
			['name' => 'American Samoa', 'code' => 'AS', 'e164_code' => '+1684'],
			['name' => 'Andorra', 'code' => 'AD', 'e164_code' => '+376'],
			['name' => 'Angola', 'code' => 'AO', 'e164_code' => '+244'],
			['name' => 'Anguilla', 'code' => 'AI', 'e164_code' => '+1264'],
			['name' => 'Antarctica', 'code' => 'AQ', 'e164_code' => '+672'],
			['name' => 'Antigua and Barbuda', 'code' => 'AG', 'e164_code' => '+1268'],
			['name' => 'Argentina', 'code' => 'AR', 'e164_code' => '+54'],
			['name' => 'Armenia', 'code' => 'AM', 'e164_code' => '+374'],
			['name' => 'Aruba', 'code' => 'AW', 'e164_code' => '+297'],
			['name' => 'Australia', 'code' => 'AU', 'e164_code' => '+61'],
			['name' => 'Austria', 'code' => 'AT', 'e164_code' => '+43'],
			['name' => 'Azerbaijan', 'code' => 'AZ', 'e164_code' => '+994'],
			['name' => 'Bahamas', 'code' => 'BS', 'e164_code' => '+1242'],
			['name' => 'Bahrain', 'code' => 'BH', 'e164_code' => '+973'],
			['name' => 'Bangladesh', 'code' => 'BD', 'e164_code' => '+880'],
			['name' => 'Barbados', 'code' => 'BB', 'e164_code' => '+1246'],
			['name' => 'Belarus', 'code' => 'BY', 'e164_code' => '+375'],
			['name' => 'Belgium', 'code' => 'BE', 'e164_code' => '+32'],
			['name' => 'Belize', 'code' => 'BZ', 'e164_code' => '+501'],
			['name' => 'Benin', 'code' => 'BJ', 'e164_code' => '+229'],
			['name' => 'Bermuda', 'code' => 'BM', 'e164_code' => '+1441'],
			['name' => 'Bhutan', 'code' => 'BT', 'e164_code' => '+975'],
			['name' => 'Bolivia', 'code' => 'BO', 'e164_code' => '+591'],
			['name' => 'Bosnia and Herzegovina', 'code' => 'BA', 'e164_code' => '+387'],
			['name' => 'Botswana', 'code' => 'BW', 'e164_code' => '+267'],
			['name' => 'Brazil', 'code' => 'BR', 'e164_code' => '+55'],
			['name' => 'British Indian Ocean Territory', 'code' => 'IO', 'e164_code' => '+246'],
			['name' => 'British Virgin Islands', 'code' => 'VG', 'e164_code' => '+1284'],
			['name' => 'Brunei', 'code' => 'BN', 'e164_code' => '+673'],
			['name' => 'Bulgaria', 'code' => 'BG', 'e164_code' => '+359'],
			['name' => 'Burkina Faso', 'code' => 'BF', 'e164_code' => '+226'],
			['name' => 'Burundi', 'code' => 'BI', 'e164_code' => '+257'],
			['name' => 'Cambodia', 'code' => 'KH', 'e164_code' => '+855'],
			['name' => 'Cameroon', 'code' => 'CM', 'e164_code' => '+237'],
			['name' => 'Canada', 'code' => 'CA', 'e164_code' => '+1'],
			['name' => 'Cape Verde', 'code' => 'CV', 'e164_code' => '+238'],
			['name' => 'Cayman Islands', 'code' => 'KY', 'e164_code' => '+1345'],
			['name' => 'Central African Republic', 'code' => 'CF', 'e164_code' => '+236'],
			['name' => 'Chad', 'code' => 'TD', 'e164_code' => '+235'],
			['name' => 'Chile', 'code' => 'CL', 'e164_code' => '+56'],
			['name' => 'China', 'code' => 'CN', 'e164_code' => '+86'],
			['name' => 'Christmas Island', 'code' => 'CX', 'e164_code' => '+61'],
			['name' => 'Cocos Islands', 'code' => 'CC', 'e164_code' => '+61'],
			['name' => 'Colombia', 'code' => 'CO', 'e164_code' => '+57'],
			['name' => 'Comoros', 'code' => 'KM', 'e164_code' => '+269'],
			['name' => 'Cook Islands', 'code' => 'CK', 'e164_code' => '+682'],
			['name' => 'Costa Rica', 'code' => 'CR', 'e164_code' => '+506'],
			['name' => 'Croatia', 'code' => 'HR', 'e164_code' => '+385'],
			['name' => 'Cuba', 'code' => 'CU', 'e164_code' => '+53'],
			['name' => 'Curacao', 'code' => 'CW', 'e164_code' => '+599'],
			['name' => 'Cyprus', 'code' => 'CY', 'e164_code' => '+357'],
			['name' => 'Czech Republic', 'code' => 'CZ', 'e164_code' => '+420'],
			['name' => 'Democratic Republic of the Congo', 'code' => 'CD', 'e164_code' => '+243'],
			['name' => 'Denmark', 'code' => 'DK', 'e164_code' => '+45'],
			['name' => 'Djibouti', 'code' => 'DJ', 'e164_code' => '+253'],
			['name' => 'Dominica', 'code' => 'DM', 'e164_code' => '+1767'],
			['name' => 'Dominican Republic', 'code' => 'DO', 'e164_code' => '+1809'],
			['name' => 'East Timor', 'code' => 'TL', 'e164_code' => '+670'],
			['name' => 'Ecuador', 'code' => 'EC', 'e164_code' => '+593'],
			['name' => 'Egypt', 'code' => 'EG', 'e164_code' => '+20'],
			['name' => 'El Salvador', 'code' => 'SV', 'e164_code' => '+503'],
			['name' => 'Equatorial Guinea', 'code' => 'GQ', 'e164_code' => '+240'],
			['name' => 'Eritrea', 'code' => 'ER', 'e164_code' => '+291'],
			['name' => 'Estonia', 'code' => 'EE', 'e164_code' => '+372'],
			['name' => 'Ethiopia', 'code' => 'ET', 'e164_code' => '+251'],
			['name' => 'Falkland Islands', 'code' => 'FK', 'e164_code' => '+500'],
			['name' => 'Faroe Islands', 'code' => 'FO', 'e164_code' => '+298'],
			['name' => 'Fiji', 'code' => 'FJ', 'e164_code' => '+679'],
			['name' => 'Finland', 'code' => 'FI', 'e164_code' => '+358'],
			['name' => 'France', 'code' => 'FR', 'e164_code' => '+33'],
			['name' => 'French Polynesia', 'code' => 'PF', 'e164_code' => '+689'],
			['name' => 'Gabon', 'code' => 'GA', 'e164_code' => '+241'],
			['name' => 'Gambia', 'code' => 'GM', 'e164_code' => '+220'],
			['name' => 'Georgia', 'code' => 'GE', 'e164_code' => '+995'],
			['name' => 'Germany', 'code' => 'DE', 'e164_code' => '+49'],
			['name' => 'Ghana', 'code' => 'GH', 'e164_code' => '+233'],
			['name' => 'Gibraltar', 'code' => 'GI', 'e164_code' => '+350'],
			['name' => 'Greece', 'code' => 'GR', 'e164_code' => '+30'],
			['name' => 'Greenland', 'code' => 'GL', 'e164_code' => '+299'],
			['name' => 'Grenada', 'code' => 'GD', 'e164_code' => '+1473'],
			['name' => 'Guam', 'code' => 'GU', 'e164_code' => '+1671'],
			['name' => 'Guatemala', 'code' => 'GT', 'e164_code' => '+502'],
			['name' => 'Guernsey', 'code' => 'GG', 'e164_code' => '+441481'],
			['name' => 'Guinea', 'code' => 'GN', 'e164_code' => '+224'],
			['name' => 'Guinea-Bissau', 'code' => 'GW', 'e164_code' => '+245'],
			['name' => 'Guyana', 'code' => 'GY', 'e164_code' => '+592'],
			['name' => 'Haiti', 'code' => 'HT', 'e164_code' => '+509'],
			['name' => 'Honduras', 'code' => 'HN', 'e164_code' => '+504'],
			['name' => 'Hong Kong', 'code' => 'HK', 'e164_code' => '+852'],
			['name' => 'Hungary', 'code' => 'HU', 'e164_code' => '+36'],
			['name' => 'Iceland', 'code' => 'IS', 'e164_code' => '+354'],
			['name' => 'India', 'code' => 'IN', 'e164_code' => '+91'],
			['name' => 'Indonesia', 'code' => 'ID', 'e164_code' => '+62'],
			['name' => 'Iran', 'code' => 'IR', 'e164_code' => '+98'],
			['name' => 'Iraq', 'code' => 'IQ', 'e164_code' => '+964'],
			['name' => 'Ireland', 'code' => 'IE', 'e164_code' => '+353'],
			['name' => 'Isle of Man', 'code' => 'IM', 'e164_code' => '+441624'],
			['name' => 'Italy', 'code' => 'IT', 'e164_code' => '+39'],
			['name' => 'Ivory Coast', 'code' => 'CI', 'e164_code' => '+225'],
			['name' => 'Jamaica', 'code' => 'JM', 'e164_code' => '+1876'],
			['name' => 'Japan', 'code' => 'JP', 'e164_code' => '+81'],
			['name' => 'Jersey', 'code' => 'JE', 'e164_code' => '+441534'],
			['name' => 'Jordan', 'code' => 'JO', 'e164_code' => '+962'],
			['name' => 'Kazakhstan', 'code' => 'KZ', 'e164_code' => '+7'],
			['name' => 'Kenya', 'code' => 'KE', 'e164_code' => '+254'],
			['name' => 'Kiribati', 'code' => 'KI', 'e164_code' => '+686'],
			['name' => 'Kosovo', 'code' => 'XK', 'e164_code' => '+383'],
			['name' => 'Kuwait', 'code' => 'KW', 'e164_code' => '+965'],
			['name' => 'Kyrgyzstan', 'code' => 'KG', 'e164_code' => '+996'],
			['name' => 'Laos', 'code' => 'LA', 'e164_code' => '+856'],
			['name' => 'Latvia', 'code' => 'LV', 'e164_code' => '+371'],
			['name' => 'Lebanon', 'code' => 'LB', 'e164_code' => '+961'],
			['name' => 'Lesotho', 'code' => 'LS', 'e164_code' => '+266'],
			['name' => 'Liberia', 'code' => 'LR', 'e164_code' => '+231'],
			['name' => 'Libya', 'code' => 'LY', 'e164_code' => '+218'],
			['name' => 'Liechtenstein', 'code' => 'LI', 'e164_code' => '+423'],
			['name' => 'Lithuania', 'code' => 'LT', 'e164_code' => '+370'],
			['name' => 'Luxembourg', 'code' => 'LU', 'e164_code' => '+352'],
			['name' => 'Macau', 'code' => 'MO', 'e164_code' => '+853'],
			['name' => 'Macedonia', 'code' => 'MK', 'e164_code' => '+389'],
			['name' => 'Madagascar', 'code' => 'MG', 'e164_code' => '+261'],
			['name' => 'Malawi', 'code' => 'MW', 'e164_code' => '+265'],
			['name' => 'Malaysia', 'code' => 'MY', 'e164_code' => '+60'],
			['name' => 'Maldives', 'code' => 'MV', 'e164_code' => '+960'],
			['name' => 'Mali', 'code' => 'ML', 'e164_code' => '+223'],
			['name' => 'Malta', 'code' => 'MT', 'e164_code' => '+356'],
			['name' => 'Marshall Islands', 'code' => 'MH', 'e164_code' => '+692'],
			['name' => 'Mauritania', 'code' => 'MR', 'e164_code' => '+222'],
			['name' => 'Mauritius', 'code' => 'MU', 'e164_code' => '+230'],
			['name' => 'Mayotte', 'code' => 'YT', 'e164_code' => '+262'],
			['name' => 'Mexico', 'code' => 'MX', 'e164_code' => '+52'],
			['name' => 'Micronesia', 'code' => 'FM', 'e164_code' => '+691'],
			['name' => 'Moldova', 'code' => 'MD', 'e164_code' => '+373'],
			['name' => 'Monaco', 'code' => 'MC', 'e164_code' => '+377'],
			['name' => 'Mongolia', 'code' => 'MN', 'e164_code' => '+976'],
			['name' => 'Montenegro', 'code' => 'ME', 'e164_code' => '+382'],
			['name' => 'Montserrat', 'code' => 'MS', 'e164_code' => '+1664'],
			['name' => 'Morocco', 'code' => 'MA', 'e164_code' => '+212'],
			['name' => 'Mozambique', 'code' => 'MZ', 'e164_code' => '+258'],
			['name' => 'Myanmar', 'code' => 'MM', 'e164_code' => '+95'],
			['name' => 'Namibia', 'code' => 'NA', 'e164_code' => '+264'],
			['name' => 'Nauru', 'code' => 'NR', 'e164_code' => '+674'],
			['name' => 'Nepal', 'code' => 'NP', 'e164_code' => '+977'],
			['name' => 'Netherlands', 'code' => 'NL', 'e164_code' => '+31'],
			['name' => 'Netherlands Antilles', 'code' => 'AN', 'e164_code' => '+599'],
			['name' => 'New Caledonia', 'code' => 'NC', 'e164_code' => '+687'],
			['name' => 'New Zealand', 'code' => 'NZ', 'e164_code' => '+64'],
			['name' => 'Nicaragua', 'code' => 'NI', 'e164_code' => '+505'],
			['name' => 'Niger', 'code' => 'NE', 'e164_code' => '+227'],
			['name' => 'Nigeria', 'code' => 'NG', 'e164_code' => '+234'],
			['name' => 'Niue', 'code' => 'NU', 'e164_code' => '+683'],
			['name' => 'North Korea', 'code' => 'KP', 'e164_code' => '+850'],
			['name' => 'Northern Mariana Islands', 'code' => 'MP', 'e164_code' => '+1670'],
			['name' => 'Norway', 'code' => 'NO', 'e164_code' => '+47'],
			['name' => 'Oman', 'code' => 'OM', 'e164_code' => '+968'],
			['name' => 'Pakistan', 'code' => 'PK', 'e164_code' => '+92'],
			['name' => 'Palau', 'code' => 'PW', 'e164_code' => '+680'],
			['name' => 'Palestine', 'code' => 'PS', 'e164_code' => '+970'],
			['name' => 'Panama', 'code' => 'PA', 'e164_code' => '+507'],
			['name' => 'Papua New Guinea', 'code' => 'PG', 'e164_code' => '+675'],
			['name' => 'Paraguay', 'code' => 'PY', 'e164_code' => '+595'],
			['name' => 'Peru', 'code' => 'PE', 'e164_code' => '+51'],
			['name' => 'Philippines', 'code' => 'PH', 'e164_code' => '+63'],
			['name' => 'Pitcairn', 'code' => 'PN', 'e164_code' => '+64'],
			['name' => 'Poland', 'code' => 'PL', 'e164_code' => '+48'],
			['name' => 'Portugal', 'code' => 'PT', 'e164_code' => '+351'],
			['name' => 'Puerto Rico', 'code' => 'PR', 'e164_code' => '+1787'],
			['name' => 'Qatar', 'code' => 'QA', 'e164_code' => '+974'],
			['name' => 'Republic of the Congo', 'code' => 'CG', 'e164_code' => '+242'],
			['name' => 'Reunion', 'code' => 'RE', 'e164_code' => '+262'],
			['name' => 'Romania', 'code' => 'RO', 'e164_code' => '+40'],
			['name' => 'Russia', 'code' => 'RU', 'e164_code' => '+7'],
			['name' => 'Rwanda', 'code' => 'RW', 'e164_code' => '+250'],
			['name' => 'Saint Barthelemy', 'code' => 'BL', 'e164_code' => '+590'],
			['name' => 'Saint Helena', 'code' => 'SH', 'e164_code' => '+290'],
			['name' => 'Saint Kitts and Nevis', 'code' => 'KN', 'e164_code' => '+1869'],
			['name' => 'Saint Lucia', 'code' => 'LC', 'e164_code' => '+1758'],
			['name' => 'Saint Martin', 'code' => 'MF', 'e164_code' => '+590'],
			['name' => 'Saint Pierre and Miquelon', 'code' => 'PM', 'e164_code' => '+508'],
			['name' => 'Saint Vincent and the Grenadines', 'code' => 'VC', 'e164_code' => '+1784'],
			['name' => 'Samoa', 'code' => 'WS', 'e164_code' => '+685'],
			['name' => 'San Marino', 'code' => 'SM', 'e164_code' => '+378'],
			['name' => 'Sao Tome and Principe', 'code' => 'ST', 'e164_code' => '+239'],
			['name' => 'Saudi Arabia', 'code' => 'SA', 'e164_code' => '+966'],
			['name' => 'Senegal', 'code' => 'SN', 'e164_code' => '+221'],
			['name' => 'Serbia', 'code' => 'RS', 'e164_code' => '+381'],
			['name' => 'Seychelles', 'code' => 'SC', 'e164_code' => '+248'],
			['name' => 'Sierra Leone', 'code' => 'SL', 'e164_code' => '+232'],
			['name' => 'Singapore', 'code' => 'SG', 'e164_code' => '+65'],
			['name' => 'Sint Maarten', 'code' => 'SX', 'e164_code' => '+1721'],
			['name' => 'Slovakia', 'code' => 'SK', 'e164_code' => '+421'],
			['name' => 'Slovenia', 'code' => 'SI', 'e164_code' => '+386'],
			['name' => 'Solomon Islands', 'code' => 'SB', 'e164_code' => '+677'],
			['name' => 'Somalia', 'code' => 'SO', 'e164_code' => '+252'],
			['name' => 'South Africa', 'code' => 'ZA', 'e164_code' => '+27'],
			['name' => 'South Korea', 'code' => 'KR', 'e164_code' => '+82'],
			['name' => 'South Sudan', 'code' => 'SS', 'e164_code' => '+211'],
			['name' => 'Spain', 'code' => 'ES', 'e164_code' => '+34'],
			['name' => 'Sri Lanka', 'code' => 'LK', 'e164_code' => '+94'],
			['name' => 'Sudan', 'code' => 'SD', 'e164_code' => '+249'],
			['name' => 'Suriname', 'code' => 'SR', 'e164_code' => '+597'],
			['name' => 'Svalbard and Jan Mayen', 'code' => 'SJ', 'e164_code' => '+47'],
			['name' => 'Swaziland', 'code' => 'SZ', 'e164_code' => '+268'],
			['name' => 'Sweden', 'code' => 'SE', 'e164_code' => '+46'],
			['name' => 'Switzerland', 'code' => 'CH', 'e164_code' => '+41'],
			['name' => 'Syria', 'code' => 'SY', 'e164_code' => '+963'],
			['name' => 'Taiwan', 'code' => 'TW', 'e164_code' => '+886'],
			['name' => 'Tajikistan', 'code' => 'TJ', 'e164_code' => '+992'],
			['name' => 'Tanzania', 'code' => 'TZ', 'e164_code' => '+255'],
			['name' => 'Thailand', 'code' => 'TH', 'e164_code' => '+66'],
			['name' => 'Togo', 'code' => 'TG', 'e164_code' => '+228'],
			['name' => 'Tokelau', 'code' => 'TK', 'e164_code' => '+690'],
			['name' => 'Tonga', 'code' => 'TO', 'e164_code' => '+676'],
			['name' => 'Trinidad and Tobago', 'code' => 'TT', 'e164_code' => '+1868'],
			['name' => 'Tunisia', 'code' => 'TN', 'e164_code' => '+216'],
			['name' => 'Turkey', 'code' => 'TR', 'e164_code' => '+90'],
			['name' => 'Turkmenistan', 'code' => 'TM', 'e164_code' => '+993'],
			['name' => 'Turks and Caicos Islands', 'code' => 'TC', 'e164_code' => '+1649'],
			['name' => 'Tuvalu', 'code' => 'TV', 'e164_code' => '+688'],
			['name' => 'U.S. Virgin Islands', 'code' => 'VI', 'e164_code' => '+1340'],
			['name' => 'Uganda', 'code' => 'UG', 'e164_code' => '+256'],
			['name' => 'Ukraine', 'code' => 'UA', 'e164_code' => '+380'],
			['name' => 'United Arab Emirates', 'code' => 'AE', 'e164_code' => '+971'],
			['name' => 'United Kingdom', 'code' => 'GB', 'e164_code' => '+44'],
			['name' => 'United States', 'code' => 'US', 'e164_code' => '+1'],
			['name' => 'Uruguay', 'code' => 'UY', 'e164_code' => '+598'],
			['name' => 'Uzbekistan', 'code' => 'UZ', 'e164_code' => '+998'],
			['name' => 'Vanuatu', 'code' => 'VU', 'e164_code' => '+678'],
			['name' => 'Vatican', 'code' => 'VA', 'e164_code' => '+379'],
			['name' => 'Venezuela', 'code' => 'VE', 'e164_code' => '+58'],
			['name' => 'Vietnam', 'code' => 'VN', 'e164_code' => '+84'],
			['name' => 'Wallis and Futuna', 'code' => 'WF', 'e164_code' => '+681'],
			['name' => 'Western Sahara', 'code' => 'EH', 'e164_code' => '+212'],
			['name' => 'Yemen', 'code' => 'YE', 'e164_code' => '+967'],
			['name' => 'Zambia', 'code' => 'ZM', 'e164_code' => '+260'],
			['name' => 'Zimbabwe', 'code' => 'ZW', 'e164_code' => '+263']
		];

		Country::insert($counties);
	}
}